"""v1.4.0

Revision ID: 1bdb18cd9fda
Revises: 9d83f75a4bc1
Create Date: 2017-11-01 08:31:33.987568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdb18cd9fda'
down_revision = '9d83f75a4bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_pitch_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'pitch_id')
    op.add_column('pitch', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'pitch', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'category_id')
    op.add_column('categories', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_pitch_id_fkey', 'categories', 'pitch', ['pitch_id'], ['id'])
    # ### end Alembic commands ###
