"""v1.6.0

Revision ID: 3e6d1c672ff8
Revises: a789a22b9ba4
Create Date: 2017-11-01 18:43:50.434822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6d1c672ff8'
down_revision = 'a789a22b9ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'pitch_author')
    op.drop_column('reviews', 'pitch_idea')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('pitch_idea', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reviews', sa.Column('pitch_author', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
