"""v1.3.5

Revision ID: 9d83f75a4bc1
Revises: b758c72a8fe2
Create Date: 2017-10-31 12:54:15.790811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d83f75a4bc1'
down_revision = 'b758c72a8fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review', sa.String(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'pitch', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'review')
    # ### end Alembic commands ###
