"""v1.3.0

Revision ID: b758c72a8fe2
Revises: 36806bb4bec8
Create Date: 2017-10-31 12:47:36.622501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b758c72a8fe2'
down_revision = '36806bb4bec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('pitch', sa.String(length=300), nullable=True))
    op.drop_column('pitch', 'idea')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('idea', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitch', 'pitch')
    # ### end Alembic commands ###
