"""v1.4.5

Revision ID: f5256e775801
Revises: 1bdb18cd9fda
Create Date: 2017-11-01 08:34:39.654825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5256e775801'
down_revision = '1bdb18cd9fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pitch_category_id_fkey', 'pitch', type_='foreignkey')
    op.create_foreign_key(None, 'pitch', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.create_foreign_key('pitch_category_id_fkey', 'pitch', 'pitch', ['category_id'], ['id'])
    # ### end Alembic commands ###
